image: gcc
before_script:
    - apt-get update --yes
    - apt-get install --yes cmake

stages:
    - build

build-cpp-job:
    stage: build
    script:
        - cmake -B build/c++ -S c++
        - cmake --build build/c++
        - cd build/c++ && ctest

build-c-job:
    stage: build
    script:
        - cmake -B build/c -S c
        - cmake --build build/c
        - cd build/c && ctest

build-c-to-c-job:
    stage: build
    script:
        - cmake -B build/c-to-c -S c-to-c
        - cmake --build build/c-to-c
        - cd build/c-to-c && ctest
