image: gcc
before_script:
 - apt-get update --yes
 - apt-get install --yes cmake

stages:
  - build

build-job:
  stage: build
  script:
    - cmake -B build -S c++
    - cmake --build build
    - cd build && ctest
