image: gcc
before_script:
 - apt-get update --yes
 - apt-get install --yes cmake

stages:
  - build

build-job:
  stage: build
  script:
    - cd c++
    - cmake --preset default
    - cmake --build --preset default
    - cd build/default && ctest
