image: ubuntu:impish
before_script:
    - apt-get update --yes
    - apt-get install --yes wget
    - wget https://packages.microsoft.com/config/ubuntu/21.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
    - dpkg -i packages-microsoft-prod.deb
    - rm packages-microsoft-prod.deb
    - apt-get update --yes
    - apt-get install --yes git g++ cmake libboost-dev apt-transport-https ninja-build
    - apt-get install --yes dotnet-sdk-6.0

stages:
    - build

build-cpp-job:
    stage: build
    script:
        - cmake -B build/c++ -S c++
        - cmake --build build/c++
        - cd build/c++ && ctest

build-c-job:
    stage: build
    script:
        - cmake -B build/c -S c
        - cmake --build build/c
        - cd build/c && ctest

build-c-to-c-job:
    stage: build
    script:
        - cmake -B build/c-to-c -S c-to-c
        - cmake --build build/c-to-c
        - cd build/c-to-c && ctest

build-cs-job:
    stage: build
    script:
        - dotnet test cs/morth.sln

build-c-pure-job:
    stage: build
    script:
        - cd c-pure && cc -o coolbuild coolbuild.c
        - cd c-pure && ./coolbuild
