name: c-pure

on:
  push:
    branches: [ main ]
    paths:
      - 'c-pure/**'
      - '.github/workflows/c-pure.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'c-pure/**'
      - '.github/workflows/c-pure.yml'

jobs:
  build:
    strategy:
      matrix:
        include:
          - { os: windows-latest, mkcoolbuild: cl.exe -NoLogo }
          - { os: ubuntu-latest, cc: cc -o coolbuild }

    runs-on: ${{ matrix.os }}

    defaults:
      run:
       working-directory: c-pure

    steps:
    - uses: actions/checkout@v3
    - uses: ilammy/msvc-dev-cmd@v1
    - name: configure
      run: ${{ matrix.mkcoolbuild }} coolbuild.c
    - name: build
      run: ./coolbuild
