name: c-pure

on:
  push:
    branches: [ main ]
    paths:
      - 'c-pure/**'
      - '.github/workflows/c-pure.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'c-pure/**'
      - '.github/workflows/c-pure.yml'

jobs:
  build:
    strategy:
      matrix:
        include:
          - { id: win-msvc, os: windows-latest, cc: cl.exe, buildargs: /nologo /Fecoolbuild.exe }
          - { id: win-clang, os: windows-latest, cc: clang, buildargs: -o coolbuild.exe }
          - { id: linux-gcc, os: ubuntu-latest, cc: gcc, buildargs: -o coolbuild }
          - { id: linux-clang, os: ubuntu-latest, cc: clang, buildargs: -o coolbuild }

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        working-directory: c-pure

    env:
      CC: ${{ matrix.cc }}

    steps:
    - uses: actions/checkout@v3
    - name: Install Clang
      uses: egor-tensin/setup-clang@v1.4
      if: matrix.cc == 'clang'
    - uses: ilammy/msvc-dev-cmd@v1
      if: matrix.os == 'windows-latest'
    - name: configure
      run: ${{ matrix.cc }} ${{ matrix.buildargs }} coolbuild.c
    - name: build
      run: ./coolbuild
