name: c-pure

on:
  push:
    branches: [ main ]
    paths:
      - 'c-pure/**'
      - '.github/workflows/c-pure.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'c-pure/**'
      - '.github/workflows/c-pure.yml'

jobs:
  build:
    strategy:
      matrix:
        include:
          - { os: windows-latest, cc: cl.exe }
          - { os: ubuntu-latest, cc: cc }

    runs-on: ${{ matrix.os }}

    defaults:
      run:
       working-directory: c-pure

    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: ${{ matrix.cc }} -o coolbuild coolbuild.c
    - name: build
      run: ./coolbuild
