name: c-pure

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    defaults:
      run:
       working-directory: c-pure 

    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: cc -o coolbuild coolbuild.c
    - name: build
      run: ./coolbuild
