name: c-pure

on:
  push:
    branches: [ main ]
    paths:
      - 'c-pure/**'
      - '.github/workflows/c-pure.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'c-pure/**'
      - '.github/workflows/c-pure.yml'

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
       working-directory: c-pure

    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: cc -o coolbuild coolbuild.c
    - name: build
      run: ./coolbuild
