name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Set up GCC
      uses: egor-tensin/setup-gcc@v1
      with:
        version: latest
        platform: x64
    - name: Restore dependencies
      working-directory: cs
      run: dotnet restore
    - name: Build
      working-directory: cs
      run: dotnet build --no-restore
    - name: Test
      working-directory: cs
      run: dotnet test --no-build --verbosity normal
